### ISSUE TITLE
[Component] Tab

### ISSUE THREAD

**Issue by turolopezsanabria** [adevinta/spark-ios#234]
Implement a segmented control as defined in tabs as shown in https://spark.adevinta.com/1186e1705/p/7461a4-tabs/b/98915d
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/245
- [ ] https://github.com/adevinta/spark-ios/issues/249
- [ ] https://github.com/adevinta/spark-ios/issues/246
- [ ] https://github.com/adevinta/spark-ios/issues/257
- [ ] https://github.com/adevinta/spark-ios/issues/270
- [ ] https://github.com/adevinta/spark-ios/issues/275
- [ ] https://github.com/adevinta/spark-ios/issues/286
- [ ] https://github.com/adevinta/spark-ios/issues/308
- [ ] https://github.com/adevinta/spark-ios/issues/311
- [ ] https://github.com/adevinta/spark-ios/issues/331
- [ ] https://github.com/adevinta/spark-ios/issues/336
- [ ] https://github.com/adevinta/spark-ios/issues/396
- [ ] https://github.com/adevinta/spark-ios/issues/422
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by michael-zimmermann** [comment]
Team findings regarding implementation details of the tabs.

# Tab item
​
The tab items:
​
Content:
- An optional icon (left)
- An optional text (center)
- An optional badge (right)
- A stackView containing all of the above
	- with medium spacing
	- leading / trailing large spacing
	- top / bottom medium spacing
​
# Tabs
​
The Tabs component:
- Contains a stackView composed of multiple Tab items
- Removes a tab from its content if it has nothing in it
- A separator under the selected tab item
- Overrides its tab items identifiers using the index
- Has a delegate and a publisher that returns the index of the selected item
- Allows addition / removal / update of items
- Has an intent:
	- Primary
	- Secondary
- Has a size:
	- extraSmall
	- small
	- medium
- Has a state:
	- enabled
	- selected
	- disabled
	- hovered
​
# Scrollable Tabs
​
The scrollable tab component:
- Containes a scrollView with a Tabs component
- ScrollView trailing should be something like `scrollView.trailingAnchor.constraint(lessThanOrEqualTo: tabs.trailingAnchor)`
- May have an indicator that shows that the content is scrollable when it's needed
- Exposes the Tabs component

**Comment by elisa-hery** [comment]
tested & validated : 
- tabs are scrollable ✅ 
- 3 sizes are available ✅ 
- tabs can contain badges ✅ 
- tabs can be icon-only ✅ 
- tabs are adaptative : they can occupy as much space as they need, OR be equally-sized (aka full width). For both options they can become scrollable ✅ 
- they can be disabled ✅ 
- hover is ok ✅ 

@michael-zimmermann FYI
