### ISSUE TITLE
[Tech] Add UIKit demo app

### ISSUE THREAD

**Issue by LouisBorleeAdevinta** [adevinta/spark-ios#295]
Demo app right now is in SwiftUI and it makes us miss some bugs with UIKit components, we need a UIKit demo to better test them
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/315
- [ ] https://github.com/adevinta/spark-ios/issues/319
- [ ] https://github.com/adevinta/spark-ios/issues/327
- [ ] https://github.com/adevinta/spark-ios/issues/334
- [ ] https://github.com/adevinta/spark-ios/issues/344
- [ ] https://github.com/adevinta/spark-ios/issues/349
- [ ] https://github.com/adevinta/spark-ios/issues/353
- [ ] https://github.com/adevinta/spark-ios/issues/357
- [ ] https://github.com/adevinta/spark-ios/issues/359
- [ ] https://github.com/adevinta/spark-ios/issues/362
- [ ] https://github.com/adevinta/spark-ios/issues/406
```
```[tasklist]
### Tasks
```
