### ISSUE TITLE
[Component] Checkbox: design changes

### ISSUE THREAD

**Issue by aycil-alican** [adevinta/spark-ios#473]
https://github.com/adevinta/spark-ios/issues/329 this task will be fixed with all design changes.
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/474
- [ ] https://github.com/adevinta/spark-ios/issues/475
- [ ] https://github.com/adevinta/spark-ios/issues/476
- [ ] https://github.com/adevinta/spark-ios/issues/477
- [ ] https://github.com/adevinta/spark-ios/issues/604
- [ ] https://github.com/adevinta/spark-ios/issues/605
```

**Comment by aycil-alican** [comment]
Checkbox design updated according figma file. It was also refactored. It is expected that the above issue https://github.com/adevinta/spark-ios/issues/329 will be resolved with the latest changes. All of checkbox components were updated and added Demo project. (UIKit, SwiftUI). All of functionality should work as expected. Wiki file was updated on github. Snapshot test will be developed with different task and swiftui part doesnt support attribute text for now.

**Comment by michael-zimmermann** [comment]
@elisa-hery 
Sorry, I've merged this to main already before you could get the chance to test it.
It needs to be tested on main.

**Comment by elisa-hery** [comment]
@michael-zimmermann @aycil-alican some comment here, nothing urgent IMO : 
1. (UI kit & swift UI) **small design issue** : on pressing, halo is always grey although it should be the intent's color (see [figma UI kit](https://www.figma.com/file/NsGfE3UnbhEyAPpVf3B60P/Spark-Components?type=design&node-id=9833%3A12653&mode=design&t=C0QjmMNvv72zj9Xb-1)) 

https://github.com/adevinta/spark-ios/assets/142396647/cfd5212f-b9b4-4bdc-93b6-5d1075d1460b



2. (UI kit) please note that I cannot test composability with other components since there is no "space container" option on demo app
3. did you improve accessibility, should I check it ?

**Comment by michael-zimmermann** [comment]
i. I've created a follow up ticket for the wrong halo color https://github.com/adevinta/spark-ios/issues/619
ii. Also a ticket: https://github.com/adevinta/spark-ios/issues/620
iii. AFAIK nothing changed on the accessibility.
