### ISSUE TITLE
[Component] Rating Display

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#526]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/589
- [ ] https://github.com/adevinta/spark-ios/issues/590
- [ ] https://github.com/adevinta/spark-ios/issues/591
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Does this ticket need to be tested ? | yes
Does this ticket need to be design reviewed ? | yes
Referent designer : | Laura
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7792-7244&mode=design&t=ZZFY1rwPpukfrZpN-0)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating)
Snapshots scenarii : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating#Rating-snapshots)
demo app : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating#Rating-demo-app-configurator)

**Comment by elisa-hery** [comment]
@michael-zimmermann it's validated on my side !
- intent ✅ 
- dark mode  ✅ 
- behaviour / rounding up  ✅ 
- half stars  ✅ 
- dynamic types (a11y)  ✅  (to check with design though)
I suggest to wait for input rating to do the design review
