### ISSUE TITLE
[Component] Progress tracker

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#534]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/743
- [ ] https://github.com/adevinta/spark-ios/issues/830
- [ ] https://github.com/adevinta/spark-ios/issues/833
- [ ] https://github.com/adevinta/spark-ios/issues/890
- [ ] https://github.com/adevinta/spark-ios/issues/895
- [ ] https://github.com/adevinta/spark-ios/issues/906
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | moderate (= should be tested by QAA before or after release)
Does this ticket need to be design reviewed ? | yes
Referent designer : | @JeremiasUX 
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=12212-6713&mode=design&t=FvppNKarxpA4HxdE-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1HAB4mAobEeHz1sJ8YihL-_HHt_OIiInYdWaCAZEj_ZM/edit#gid=1926623587)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker#Progress+tracker-demo-app-configurator)

**Comment by elisa-hery** [comment]
@michael-zimmermann a few comments / questions after testing : 

**1. about indicators content** : it seems bigger on the demo app than on the specs (see example below). Is the size up to the consumer ? 

demo app : 
![Image](https://github.com/adevinta/spark-ios/assets/142396647/9337d535-f619-4026-aa2b-e0c881a9e758)

specs : 
<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/2b826199-89cd-437f-af7f-aedab38c85f6" width="80px">
</picture>


**2. Sometimes spaces are not homogeneous between indicators**
To reproduce : horizontal progress tracker with 4 indicators (no matter the size) and label "lorem ipsum" --> hopefully you'll see the bug


<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/73047eab-602b-4e23-8328-0ca5df9509cd" width="300px">
</picture>

<br/><br/>
**3. a question about spacing for vertical alignement (medium & large size)**. There in not much space between progress indicators when label takes only 1 line. Can consumer change the progress track size ?

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/fc79c9a2-9c98-4cfc-b4ea-2377bc469c5e" width="200px">
</picture>

**4. something that could be blocking but I have trouble to reproduce** : sometimes I have to click several times on the progress indicator before it's selected (at the end of the video below it's really visible). I feel this is easier to reproduce with bigger dynamic types, and text content, but I'm not sure.


https://github.com/adevinta/spark-ios/assets/142396647/e547a901-93a3-4ead-9666-3c5082b21466

**Comment by michael-zimmermann** [comment]
### 1 Indicator content
The image size is 16x16 just as defined in the specs. It may be, that I have a different image 
<img width="1160" alt="Bildschirmfoto 2024-04-19 um 12 28 07" src="https://github.com/adevinta/spark-ios/assets/128726463/55e7b8ec-b0d9-4e95-8d2f-5ec19d33f35a">
The differences may be due to the images that are used. I used the checkmark image, that is also used for the checkboxes. But the user can define any image they want for this.

**Comment by elisa-hery** [comment]
@michael-zimmermann I tested the fixes and everything is ok. So, to recap : 
1. ok ✅ 
2. ok ✅ 
3. ok ✅ 
4. ok fixed ✅ 
5. about the new bug you found on vertical orientation and labels cropped : it's fixed ⬇  ✅ 

<picture>
  <img alt="specs" src="https://github.com/adevinta/spark-ios/assets/142396647/7cad82b2-e149-4209-bef2-83b6950167de" width="200px">
</picture>


I'm moving this ticket to RFP 🥳

**Comment by JeremiasUX** [comment]
SIze: Large
Frame width/height: 150
If you change the frame width to 150 the progress tracker looks broken (image)

![Image](https://github.com/adevinta/spark-ios/assets/139337913/249e9a74-6829-472a-9284-56c99208a68f)

**Comment by JeremiasUX** [comment]
In this case the first icon looks pretty small. I activated the "current page indicator"

![Image](https://github.com/adevinta/spark-ios/assets/139337913/20b03fde-e94b-423e-9d31-a9d05f0f4c17)

**Comment by michael-zimmermann** [comment]
> In this case the first icon looks pretty small. I activated the "current page indicator"

I used different icons. All Icons are 16 x 16px. The first Icon has a circle around it, that's why it looks smaller.
