### ISSUE TITLE
[Component] Progress tracker

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-ios#536]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-ios/issues/740
- [ ] https://github.com/adevinta/spark-ios/issues/741
- [ ] https://github.com/adevinta/spark-ios/issues/742
- [ ] https://github.com/adevinta/spark-ios/issues/780
- [ ] https://github.com/adevinta/spark-ios/issues/790
- [ ] https://github.com/adevinta/spark-ios/issues/799
- [ ] https://github.com/adevinta/spark-ios/issues/824
- [ ] https://github.com/adevinta/spark-ios/issues/831
```

**Comment by michael-zimmermann** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | 
Does this ticket need to be design reviewed ? | yes
Referent designer : | @JeremiasUX 
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=12212-6713&mode=design&t=FvppNKarxpA4HxdE-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1HAB4mAobEeHz1sJ8YihL-_HHt_OIiInYdWaCAZEj_ZM/edit#gid=1926623587)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker#Progress+tracker-demo-app-configurator)

**Comment by elisa-hery** [comment]
All the bugs are fixed ✅  (see details [here](https://docs.google.com/spreadsheets/d/1iwhA0Qv113B2DBrVcXzWRNzm3oUrtCFWC_0dZEvYYrM/edit#gid=139525665))

**Comment by elisa-hery** [comment]
Will be released when @michael-zimmermann will be back
